---
title: "Shine bright like a diamond"
output: 
  html_document: 
    highlight: pygments
    theme: flatly
---

Create a scatterplot of two numerical variables in the `diamonds` dataset. This should be an 
interactive plot created with `shiny` such that the user selects the variable to be placed on 
the x and y axes from a drop down menu. You can place that drop down menu on the sidebar 
(like in the class example), or feel free to get creative with it...

Then, add functionality to color the points on the scatterplot by a categorical variable
in the dataset. The user should also be able to choose the categorical variable from a 
drop down menu.

#### Tips

- Go through the `diamonds` dataset and decide which variables are categorical and which
are numerical.

- Then, first make a static version of a plot so that you develop the `ggplot2` code. Then
work on building the app by wrapping it in `shiny` code.

- Feel free to use whatever code from the class demo you find is useful / relevant. Code
is available [here](https://github.com/mine-cetinkaya-rundel/sta112_f15/tree/master/shiny_clt).

### Accessing the data

Once the `ggplot2` package is loaded, you can load the dataset with

```{r eval=FALSE}
data(diamonds)
```

### Submission instructions

Your submission should be an R Markdown file in your team App Ex repo, in a folder 
called `AppEx_10`.

### Due date

Tuesday, Nov 17, by class

### Watch out for...

merge conflics on GitHub -- you're working in the same repo now!

Issues will arise, and that's fine! Commit and push often, and ask questions
when stuck.